`timescale 1ns/1ps

module IIR_tb();
    //Parameters
    parameter DATA_W = 16;
    parameter CLK_PERIOD = 167; // 1/(6 MHz) approx 167 ns
    //Ports
    reg clk;
    reg rst_n;
    reg signed [DATA_W-1:0] x;
    wire signed [DATA_W-1:0] y;
    //File I/O Variables
    integer input_file;
    integer output_file;
    integer status; // To check file read status
    integer sample_count;
    integer x_data; // Temporary variable to read input as decimal integer

    //Instantiate DUT (Device Under Test)
    // Ensure the parameters here match the ones in Notch_IIR.v
    Notch_IIR #(.COEFF_W(16),.DATA_W(16),.STATE_W(64),.ACC_W(64)) 
              DUT (.clk(clk),.rst_n(rst_n),.x(x),.y(y));
    
    //Clock Generation
    initial begin
        clk = 0;
        forever begin
          #(CLK_PERIOD/2) clk = ~clk;  
        end 
    end

    //Main Test Sequence
    initial begin
        // 1. File Setup
        // Open the fixed-point input file generated by Python
        input_file = $fopen("input_fixed_point.txt", "r");
        // Open the output file for Verilog results
        output_file = $fopen("verilog_output_fixed.txt", "w");

        if (input_file == 0) begin
            $display("ERROR: Could not open input_fixed_point.txt");
            $stop;
        end
        if (output_file == 0) begin
            $display("ERROR: Could not open verilog_output_fixed.txt");
            $stop;
        end
        
        // 2. Initialization and Reset
        rst_n = 0;
        x = 0;
        sample_count = 0;
        repeat(2) @(negedge clk);
        rst_n = 1; // De-assert reset after two clock cycles

        // 3. Read Input File and Run Simulation
        $display("Reading input samples and applying to DUT...");
        
        // Loop while not at the end of the input file
        while (!$feof(input_file)) begin
            
            // Read one signed decimal value from the file (%d)
            status = $fscanf(input_file, "%d\n", x_data);
            
            if (status == 1) begin // Check if read was successful
                // Apply the fixed-point data to the input 'x'
                x = x_data;
                
                // Wait one full clock cycle to process the sample
                // The output 'y' and the internal states (s1, s2) update here.
                @(negedge clk);
                
                // Write the filtered output (y) to the output file
                // Output is written as a signed decimal integer (s16.15 value)
                $fwrite(output_file, "%d\n", $signed(y)); 
                
                sample_count = sample_count + 1;
            end else if (status != 0) begin
                // Handle read error (e.g., empty line or corrupted data)
                $display("Warning: File read status check failed. Status: %0d", status);
            end
        end

        // 4. Cleanup and Finish
        repeat(5) @(negedge clk); // Wait a few more cycles for any final pipeline stages (good practice)
        
        $fclose(input_file);
        $fclose(output_file);
        
        $display("Finished processing %0d samples.", sample_count);
        $display("Verilog output saved to verilog_output_fixed.txt");
        $stop; // Stop simulation
    end

    // VCD DUMP: Use Questasim's native Wave Viewer
    initial begin
        $dumpfile("IIR_tb.vcd");
        $dumpvars(0, IIR_tb);
    end

endmodule